"""Code Generation Service - Visual Diagram to Terraform"""

import logging
from typing import Dict, List, Any, Tuple
import json
from datetime import datetime

logger = logging.getLogger(__name__)


class CodeGeneratorService:
    """Generate Terraform code from visual diagrams"""

    def __init__(self):
        self.component_templates = self._load_component_templates()

    def _load_component_templates(self) -> Dict[str, Any]:
        """Load component templates"""
        # In production, load from database
        # For now, return hardcoded templates
        return {
            "azure-vnet": {
                "terraform_module": "../../modules/networking/azure-vnet",
                "resource_name": "azurerm_virtual_network",
            },
            "azure-subnet": {
                "terraform_module": "../../modules/networking/azure-subnet",
                "resource_name": "azurerm_subnet",
            },
            "azure-nsg": {
                "terraform_module": "../../modules/networking/azure-nsg",
                "resource_name": "azurerm_network_security_group",
            },
            "azure-vm": {
                "terraform_module": "../../modules/compute/azure-vm",
                "resource_name": "azurerm_linux_virtual_machine",
            },
            "azure-storage": {
                "terraform_module": "../../modules/shared-services/azure-storage-account",
                "resource_name": "azurerm_storage_account",
            },
        }

    def generate_terraform(
        self,
        diagram: Dict[str, Any],
        configuration: Dict[str, Any],
        project_name: str,
    ) -> Dict[str, str]:
        """
        Generate Terraform files from diagram and configuration.

        Args:
            diagram: Visual diagram data (nodes + edges)
            configuration: YAML configuration
            project_name: Project name

        Returns:
            Dictionary of filename: content
        """
        logger.info(f"Generating Terraform for project: {project_name}")

        files = {}

        # 1. Generate main.tf
        files["main.tf"] = self._generate_main_tf(diagram, configuration, project_name)

        # 2. Generate variables.tf
        files["variables.tf"] = self._generate_variables_tf(diagram, configuration)

        # 3. Generate outputs.tf
        files["outputs.tf"] = self._generate_outputs_tf(diagram)

        # 4. Generate versions.tf
        files["versions.tf"] = self._generate_versions_tf()

        # 5. Generate terraform.tfvars (if needed)
        if configuration.get("variables"):
            files["terraform.tfvars"] = self._generate_tfvars(configuration)

        # 6. Generate README.md
        files["README.md"] = self._generate_readme(diagram, configuration, project_name)

        logger.info(f"Generated {len(files)} Terraform files")

        return files

    def _generate_main_tf(
        self,
        diagram: Dict[str, Any],
        configuration: Dict[str, Any],
        project_name: str,
    ) -> str:
        """Generate main.tf"""
        nodes = diagram.get("nodes", [])
        edges = diagram.get("edges", [])

        # Sort nodes by dependencies (topological sort)
        sorted_nodes = self._topological_sort(nodes, edges)

        # Generate header
        content = f"""# Generated by Visual IaC Designer
# Project: {project_name}
# Generated: {datetime.utcnow().isoformat()}

"""

        # Generate resource group (if not exists)
        content += """# Resource Group
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

"""

        # Generate modules for each node
        for node in sorted_nodes:
            content += self._generate_module_block(node, configuration, edges)
            content += "\n\n"

        return content

    def _generate_module_block(
        self,
        node: Dict[str, Any],
        configuration: Dict[str, Any],
        edges: List[Dict[str, Any]],
    ) -> str:
        """Generate a Terraform module block for a node"""
        node_id = node["id"]
        node_type = node["type"]
        node_data = node.get("data", {})

        # Get component template
        template = self.component_templates.get(node_type, {})
        module_source = template.get("terraform_module", "local")

        # Get configuration for this node
        node_config = configuration.get("resources", {}).get(node_id, {}).get("config", {})

        # Merge node data with configuration
        merged_config = {**node_data, **node_config}

        # Generate module name (sanitize node_id)
        module_name = node_id.replace("-", "_").replace(" ", "_").lower()

        # Start module block
        content = f"""# {merged_config.get('name', module_name)}
module "{module_name}" {{
  source = "{module_source}"

"""

        # Add required arguments
        content += f'  resource_group_name = azurerm_resource_group.main.name\n'
        content += f'  location            = var.location\n'

        # Add configuration parameters
        for key, value in merged_config.items():
            if key in ["position", "id", "type"]:
                continue

            content += self._format_terraform_argument(key, value)

        # Add dependencies
        dependencies = self._get_dependencies(node_id, edges)
        if dependencies:
            dep_list = [f"module.{dep.replace('-', '_')}" for dep in dependencies]
            content += f'\n  depends_on = [{", ".join(dep_list)}]\n'

        # Add custom overrides
        node_overrides = configuration.get("resources", {}).get(node_id, {}).get("overrides", {})
        if node_overrides.get("terraform"):
            content += f'\n  # Custom overrides\n'
            content += node_overrides["terraform"]
            content += '\n'

        content += "}"

        return content

    def _format_terraform_argument(self, key: str, value: Any) -> str:
        """Format a Terraform argument"""
        if isinstance(value, str):
            return f'  {key:20s} = "{value}"\n'
        elif isinstance(value, bool):
            return f'  {key:20s} = {str(value).lower()}\n'
        elif isinstance(value, (int, float)):
            return f'  {key:20s} = {value}\n'
        elif isinstance(value, list):
            if all(isinstance(item, str) for item in value):
                items = ", ".join(f'"{item}"' for item in value)
                return f'  {key:20s} = [{items}]\n'
            else:
                return f'  {key:20s} = {json.dumps(value)}\n'
        elif isinstance(value, dict):
            return f'  {key:20s} = {json.dumps(value)}\n'
        else:
            return f'  {key:20s} = {json.dumps(value)}\n'

    def _topological_sort(
        self,
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Sort nodes by dependencies (topological sort)"""
        # Create dependency graph
        graph: Dict[str, List[str]] = {node["id"]: [] for node in nodes}
        in_degree: Dict[str, int] = {node["id"]: 0 for node in nodes}

        for edge in edges:
            source = edge["source"]
            target = edge["target"]

            if source in graph and target in graph:
                graph[source].append(target)
                in_degree[target] += 1

        # Topological sort (Kahn's algorithm)
        queue = [node_id for node_id, degree in in_degree.items() if degree == 0]
        sorted_ids = []

        while queue:
            current = queue.pop(0)
            sorted_ids.append(current)

            for neighbor in graph[current]:
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)

        # Map back to node objects
        node_map = {node["id"]: node for node in nodes}
        return [node_map[node_id] for node_id in sorted_ids if node_id in node_map]

    def _get_dependencies(
        self,
        node_id: str,
        edges: List[Dict[str, Any]],
    ) -> List[str]:
        """Get dependencies for a node"""
        dependencies = []
        for edge in edges:
            if edge["target"] == node_id:
                dependencies.append(edge["source"])
        return dependencies

    def _generate_variables_tf(
        self,
        diagram: Dict[str, Any],
        configuration: Dict[str, Any],
    ) -> str:
        """Generate variables.tf"""
        content = """# Variables

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "eastus"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "development"
}

variable "tags" {
  description = "Resource tags"
  type        = map(string)
  default     = {}
}

"""

        # Add custom variables from configuration
        custom_vars = configuration.get("variables", {})
        for var_name, var_config in custom_vars.items():
            content += f'variable "{var_name}" {{\n'
            if var_config.get("description"):
                content += f'  description = "{var_config["description"]}"\n'
            if var_config.get("type"):
                content += f'  type        = {var_config["type"]}\n'
            if "default" in var_config:
                content += f'  default     = {json.dumps(var_config["default"])}\n'
            content += '}\n\n'

        return content

    def _generate_outputs_tf(self, diagram: Dict[str, Any]) -> str:
        """Generate outputs.tf"""
        nodes = diagram.get("nodes", [])

        content = "# Outputs\n\n"

        for node in nodes:
            node_id = node["id"]
            module_name = node_id.replace("-", "_").lower()
            node_name = node.get("data", {}).get("name", module_name)

            # Add ID output
            content += f"""output "{module_name}_id" {{
  description = "{node_name} ID"
  value       = module.{module_name}.id
}}

"""

        return content

    def _generate_versions_tf(self) -> str:
        """Generate versions.tf"""
        return """# Terraform and Provider Versions

terraform {
  required_version = ">= 1.8.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.0.0, < 5.0.0"
    }
  }
}

provider "azurerm" {
  features {}
}
"""

    def _generate_tfvars(self, configuration: Dict[str, Any]) -> str:
        """Generate terraform.tfvars"""
        content = "# Terraform Variables\n\n"

        variables = configuration.get("variables", {})
        for var_name, var_config in variables.items():
            if "value" in var_config:
                value = var_config["value"]
                if isinstance(value, str):
                    content += f'{var_name} = "{value}"\n'
                else:
                    content += f'{var_name} = {json.dumps(value)}\n'

        return content

    def _generate_readme(
        self,
        diagram: Dict[str, Any],
        configuration: Dict[str, Any],
        project_name: str,
    ) -> str:
        """Generate README.md"""
        nodes = diagram.get("nodes", [])

        content = f"""# {project_name}

**Generated by Visual IaC Designer**

## Overview

This infrastructure was designed visually and generated automatically.

## Resources

This configuration creates the following Azure resources:

"""

        # List resources
        for node in nodes:
            node_type = node["type"]
            node_name = node.get("data", {}).get("name", "unnamed")
            content += f"- **{node_type}**: {node_name}\n"

        content += """

## Deployment

### Prerequisites

- Terraform >= 1.8.0
- Azure CLI
- Appropriate Azure credentials

### Deploy

```bash
# Initialize
terraform init

# Plan
terraform plan

# Apply
terraform apply
```

## Configuration

Edit `terraform.tfvars` to customize the deployment.

## Generated Files

- `main.tf` - Main resource definitions
- `variables.tf` - Input variables
- `outputs.tf` - Output values
- `versions.tf` - Provider versions
- `terraform.tfvars` - Variable values

---

*Generated: """ + datetime.utcnow().isoformat() + "*\n"

        return content

    def validate(
        self,
        diagram: Dict[str, Any],
        configuration: Dict[str, Any],
    ) -> Tuple[bool, List[Dict[str, Any]], List[Dict[str, Any]]]:
        """
        Validate diagram and configuration.

        Returns:
            (is_valid, errors, warnings)
        """
        errors = []
        warnings = []

        nodes = diagram.get("nodes", [])
        edges = diagram.get("edges", [])

        # Check for circular dependencies
        if self._has_circular_dependencies(nodes, edges):
            errors.append({
                "node_id": "diagram",
                "field": "dependencies",
                "message": "Circular dependencies detected",
                "severity": "error",
            })

        # Validate each node
        for node in nodes:
            node_id = node["id"]
            node_type = node["type"]
            node_data = node.get("data", {})

            # Check if component type is supported
            if node_type not in self.component_templates:
                errors.append({
                    "node_id": node_id,
                    "field": "type",
                    "message": f"Unsupported component type: {node_type}",
                    "severity": "error",
                })

            # Check required fields
            if not node_data.get("name"):
                errors.append({
                    "node_id": node_id,
                    "field": "name",
                    "message": "Name is required",
                    "severity": "error",
                })

        is_valid = len(errors) == 0

        return is_valid, errors, warnings

    def _has_circular_dependencies(
        self,
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
    ) -> bool:
        """Check for circular dependencies"""
        graph: Dict[str, List[str]] = {node["id"]: [] for node in nodes}

        for edge in edges:
            source = edge["source"]
            target = edge["target"]
            if source in graph:
                graph[source].append(target)

        # DFS to detect cycles
        visited = set()
        rec_stack = set()

        def has_cycle(node: str) -> bool:
            visited.add(node)
            rec_stack.add(node)

            for neighbor in graph.get(node, []):
                if neighbor not in visited:
                    if has_cycle(neighbor):
                        return True
                elif neighbor in rec_stack:
                    return True

            rec_stack.remove(node)
            return False

        for node_id in graph:
            if node_id not in visited:
                if has_cycle(node_id):
                    return True

        return False
